// Code generated by tfutils/conv/gen. DO NOT EDIT.
package formation

import (
	core2 "github.com/gamefabric/terraform-provider-gamefabric/internal/resource/core"
	"github.com/gamefabric/terraform-provider-gamefabric/internal/validators"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type FormationModel struct {
	Name        types.String        `tfsdk:"name"`
	Environment types.String        `tfsdk:"environment"`
	Spec        *FormationSpecModel `tfsdk:"spec"`
}

type FormationSpecModel struct {
	Description             types.String                        `tfsdk:"description"`
	Vessels                 []VesselTemplateModel               `tfsdk:"vessels"`
	Template                *GameServerTemplateSpecModel        `tfsdk:"template"`
	VolumeTemplates         []VolumeTemplateModel               `tfsdk:"volume_templates"`
	TerminationGracePeriods *VesselTerminationGracePeriodsModel `tfsdk:"termination_grace_periods"`
}

type VesselTemplateModel struct {
	Name                    types.String                        `tfsdk:"name"`
	Description             types.String                        `tfsdk:"description"`
	Suspend                 types.Bool                          `tfsdk:"suspend"`
	Region                  types.String                        `tfsdk:"region"`
	Override                *VesselOverrideModel                `tfsdk:"override"`
	TerminationGracePeriods *VesselTerminationGracePeriodsModel `tfsdk:"termination_grace_periods"`
}

type VesselOverrideModel struct {
	Labels     types.Map                      `tfsdk:"labels"`
	Containers []VesselContainerOverrideModel `tfsdk:"containers"`
}

type VesselContainerOverrideModel struct {
	Command types.List          `tfsdk:"command"`
	Args    types.List          `tfsdk:"args"`
	Env     []core2.EnvVarModel `tfsdk:"env"`
}

type VolumeTemplateModel struct {
	Labels      map[string]types.String  `tfsdk:"labels"`
	Annotations map[string]types.String  `tfsdk:"annotations"`
	Spec        *VolumeTemplateSpecModel `tfsdk:"spec"`
}

type VolumeTemplateSpecModel struct {
	VolumeStoreName types.String `tfsdk:"volume_store_name"`
	Capacity        types.String `tfsdk:"capacity"`
	ReclaimPolicy   types.String `tfsdk:"reclaim_policy"`
}

func FormationAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"name": schema.StringAttribute{
			Description:         "The unique object name within its scope.",
			MarkdownDescription: "The unique object name within its scope.",
			Optional:            true,
			Computed:            true,
			Validators: []validator.String{
				validators.NameValidator{},
			},
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.RequiresReplace(),
			},
		},
		"environment": schema.StringAttribute{
			Description:         "The name of the environment the resource belongs to.",
			MarkdownDescription: "The name of the environment the resource belongs to.",
			Optional:            true,
			Computed:            true,
			Validators: []validator.String{
				validators.EnvironmentValidator{},
			},
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.RequiresReplace(),
			},
		},
		"spec": schema.SingleNestedAttribute{
			Description:         "Spec defines the desired vessels in this formation.",
			MarkdownDescription: "Spec defines the desired vessels in this formation.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"description": schema.StringAttribute{
					Description:         "Description is the optional description of the formation.",
					MarkdownDescription: "Description is the optional description of the formation.",
					Optional:            true,
				},
				"vessels": schema.ListNestedAttribute{
					Description:         "Vessels is a list of vessels belonging to the formation.",
					MarkdownDescription: "Vessels is a list of vessels belonging to the formation.",
					Required:            true,
					NestedObject: schema.NestedAttributeObject{
						Attributes: map[string]schema.Attribute{
							"name": schema.StringAttribute{
								Description:         "Name is the name of the vessel.",
								MarkdownDescription: "Name is the name of the vessel.",
								Required:            true,
							},
							"description": schema.StringAttribute{
								Description:         "Description is the optional description of the vessel.",
								MarkdownDescription: "Description is the optional description of the vessel.",
								Optional:            true,
							},
							"suspend": schema.BoolAttribute{
								Description:         "Suspend specifies whether the vessel should create a game server or not.",
								MarkdownDescription: "Suspend specifies whether the vessel should create a game server or not.",
								Optional:            true,
							},
							"region": schema.StringAttribute{
								Description:         "Region defines the region the vessel is deployed to.",
								MarkdownDescription: "Region defines the region the vessel is deployed to.",
								Required:            true,
							},
							"override": schema.SingleNestedAttribute{
								Description:         "Override describes how the game server is configured for this vessel.",
								MarkdownDescription: "Override describes how the game server is configured for this vessel.",
								Optional:            true,
								Attributes: map[string]schema.Attribute{
									"labels": schema.MapAttribute{
										Description:         "Labels is a map of keys and values that can be used to organize and categorize objects.",
										MarkdownDescription: "Labels is a map of keys and values that can be used to organize and categorize objects.",
										Optional:            true,
										ElementType:         types.StringType,
									},
									"containers": schema.ListNestedAttribute{
										Description:         "Containers is a list of container override values.",
										MarkdownDescription: "Containers is a list of container override values.",
										Optional:            true,
										NestedObject: schema.NestedAttributeObject{
											Attributes: map[string]schema.Attribute{
												"command": schema.ListAttribute{
													Description:         "Command is the entrypoint array. This is not executed within a shell.",
													MarkdownDescription: "Command is the entrypoint array. This is not executed within a shell.",
													Optional:            true,
													ElementType:         types.StringType,
												},
												"args": schema.ListAttribute{
													Description:         "Args are arguments to the entrypoint.",
													MarkdownDescription: "Args are arguments to the entrypoint.",
													Optional:            true,
													ElementType:         types.StringType,
												},
												"env": schema.ListNestedAttribute{
													Description:         "Env is a list of environment variables to set on containers.",
													MarkdownDescription: "Env is a list of environment variables to set on containers.",
													Optional:            true,
													NestedObject: schema.NestedAttributeObject{
														Attributes: core2.EnvVarAttributes(nil, ""),
													},
												},
											},
										},
									},
								},
							},
							"termination_grace_periods": schema.SingleNestedAttribute{
								Description:         "TerminationGracePeriods are the optional durations that a game server has to terminate gracefully. If this value is nil, the default grace period for each situation will be used. These durations only apply when a game server is in use.",
								MarkdownDescription: "TerminationGracePeriods are the optional durations that a game server has to terminate gracefully. If this value is nil, the default grace period for each situation will be used. These durations only apply when a game server is in use.",
								Optional:            true,
								Attributes:          VesselTerminationGracePeriodsAttributes(),
							},
						},
					},
				},
				"template": schema.SingleNestedAttribute{
					Description:         "Template describes the game server that is created.",
					MarkdownDescription: "Template describes the game server that is created.",
					Required:            true,
					Attributes:          GameServerTemplateSpecAttributes(),
				},
				"volume_templates": schema.ListNestedAttribute{
					Description:         "VolumeTemplates is a list of volumes that vessels are allowed to reference.",
					MarkdownDescription: "VolumeTemplates is a list of volumes that vessels are allowed to reference.",
					Optional:            true,
					NestedObject: schema.NestedAttributeObject{
						Attributes: map[string]schema.Attribute{
							"metadata": schema.SingleNestedAttribute{
								Description:         "Standard object&#39;s metadata.",
								MarkdownDescription: "Standard object&#39;s metadata.",
								Optional:            true,
								Attributes: map[string]schema.Attribute{
									"labels": schema.MapAttribute{
										Description:         "A map of keys and values that can be used to organize and categorize objects.",
										MarkdownDescription: "A map of keys and values that can be used to organize and categorize objects.",
										Optional:            true,
										ElementType:         types.StringType,
									},
									"annotations": schema.MapAttribute{
										Description:         "An unstructured map of keys and values stored on an object.",
										MarkdownDescription: "An unstructured map of keys and values stored on an object.",
										Optional:            true,
										ElementType:         types.StringType,
									},
								},
							},
							"spec": schema.SingleNestedAttribute{
								Description:         "Spec defines the desired volume template.",
								MarkdownDescription: "Spec defines the desired volume template.",
								Optional:            true,
								Attributes: map[string]schema.Attribute{
									"volume_store_name": schema.StringAttribute{
										Description:         "VolumeStoreName is the name of the volume store this volume uses.",
										MarkdownDescription: "VolumeStoreName is the name of the volume store this volume uses.",
										Required:            true,
									},
									"capacity": schema.StringAttribute{
										Description:         "Capacity is the capacity of the volume.",
										MarkdownDescription: "Capacity is the capacity of the volume.",
										Required:            true,
									},
									"reclaim_policy": schema.StringAttribute{
										Optional: true,
									},
								},
							},
						},
					},
				},
				"termination_grace_periods": schema.SingleNestedAttribute{
					Description:         "TerminationGracePeriods are the optional durations that a game server has to terminate gracefully. If this value is nil, the default grace period for each situation will be used. These durations only apply when a game server is in use.",
					MarkdownDescription: "TerminationGracePeriods are the optional durations that a game server has to terminate gracefully. If this value is nil, the default grace period for each situation will be used. These durations only apply when a game server is in use.",
					Optional:            true,
					Attributes: map[string]schema.Attribute{
						"maintenance": schema.Int64Attribute{
							Description:         "Maintenance is the optional duration in seconds that a game server has to gracefully terminate when the site it is running is cordoned.",
							MarkdownDescription: "Maintenance is the optional duration in seconds that a game server has to gracefully terminate when the site it is running is cordoned.",
							Optional:            true,
						},
						"spec_change": schema.Int64Attribute{
							Description:         "SpecChange is the optional duration in seconds that a game server has to gracefully terminate when a spec change is detected.",
							MarkdownDescription: "SpecChange is the optional duration in seconds that a game server has to gracefully terminate when a spec change is detected.",
							Optional:            true,
						},
						"user_initiated": schema.Int64Attribute{
							Description:         "UserInitiated is the optional duration in seconds that a game server has to gracefully terminate when user initiates a restart or suspends a vessel.",
							MarkdownDescription: "UserInitiated is the optional duration in seconds that a game server has to gracefully terminate when user initiates a restart or suspends a vessel.",
							Optional:            true,
						},
					},
				},
			},
		},
	}
}
