// Code generated by tfutils/conv/gen. DO NOT EDIT.
package core

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/objectvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
)

func EnvVarAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"name": schema.StringAttribute{
			Description:         "Name is the name of the environment variable.",
			MarkdownDescription: "Name is the name of the environment variable.",
			Required:            true,
		},
		"value": schema.StringAttribute{
			Description:         "Value is the value of the environment variable.",
			MarkdownDescription: "Value is the value of the environment variable.",
			Optional:            true,
			Validators: []validator.String{
				stringvalidator.ExactlyOneOf(path.MatchRelative().AtParent().AtName("value_from")),
			},
		},
		"value_from": schema.SingleNestedAttribute{
			Description:         "ValueFrom is the source for the environment variable&#39;s value.",
			MarkdownDescription: "ValueFrom is the source for the environment variable&#39;s value.",
			Optional:            true,
			Attributes: map[string]schema.Attribute{
				"field_ref": schema.SingleNestedAttribute{
					Description:         "FieldRef selects the field of the pod. Supports metadata.name, metadata.namespace, `metadata.labels['<KEY>']`, `metadata.annotations['<KEY>']`, metadata.armadaName, metadata.regionName, metadata.regionTypeName, metadata.siteName, metadata.imageBranch, metadata.imageName, metadata.imageTag, spec.nodeName, spec.serviceAccountName, status.hostIP, status.podIP, status.podIPs.",
					MarkdownDescription: "FieldRef selects the field of the pod. Supports metadata.name, metadata.namespace, `metadata.labels['<KEY>']`, `metadata.annotations['<KEY>']`, metadata.armadaName, metadata.regionName, metadata.regionTypeName, metadata.siteName, metadata.imageBranch, metadata.imageName, metadata.imageTag, spec.nodeName, spec.serviceAccountName, status.hostIP, status.podIP, status.podIPs.",
					Optional:            true,
					Attributes: map[string]schema.Attribute{
						"api_version": schema.StringAttribute{
							Required: true,
						},
						"field_path": schema.StringAttribute{
							Required: true,
						},
					},
					Validators: []validator.Object{
						objectvalidator.ExactlyOneOf(path.MatchRelative().AtParent().AtName("config_file_key_ref")),
					},
				},
				"config_file_key_ref": schema.SingleNestedAttribute{
					Description:         "ConfigFileKeyRef select the configuration file.",
					MarkdownDescription: "ConfigFileKeyRef select the configuration file.",
					Optional:            true,
					Attributes: map[string]schema.Attribute{
						"name": schema.StringAttribute{
							Description:         "Name is the name of the configuration file.",
							MarkdownDescription: "Name is the name of the configuration file.",
							Required:            true,
						},
					},
					Validators: []validator.Object{
						objectvalidator.ExactlyOneOf(path.MatchRelative().AtParent().AtName("field_ref")),
					},
				},
			},
			Validators: []validator.Object{
				objectvalidator.ExactlyOneOf(path.MatchRelative().AtParent().AtName("value")),
			},
		},
	}
}
