// Code generated by tfutils/conv/gen. DO NOT EDIT.
package armada

import (
	"github.com/gamefabric/terraform-provider-gamefabric/internal/validators"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type ArmadaSetModel struct {
	Name        types.String            `tfsdk:"name"`
	Environment types.String            `tfsdk:"environment"`
	Description types.String            `tfsdk:"description"`
	Regions     []ArmadaTemplateModel   `tfsdk:"regions"`
	Autoscaling *ArmadaAutoscalingModel `tfsdk:"autoscaling"`
	Template    *FleetTemplateSpecModel `tfsdk:"template"`
}

type ArmadaTemplateModel struct {
	Name     types.String         `tfsdk:"name"`
	Replicas []ArmadaReplicaModel `tfsdk:"repicas"`
}

func ArmadaSetAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"name": schema.StringAttribute{
			Description:         "The unique object name within its scope.",
			MarkdownDescription: "The unique object name within its scope.",
			Optional:            true,
			Computed:            true,
			Validators: []validator.String{
				validators.NameValidator{},
			},
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.RequiresReplace(),
			},
		},
		"environment": schema.StringAttribute{
			Description:         "The name of the environment the object belongs to.",
			MarkdownDescription: "The name of the environment the object belongs to.",
			Optional:            true,
			Computed:            true,
			Validators: []validator.String{
				validators.EnvironmentValidator{},
			},
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.RequiresReplace(),
			},
		},
		"description": schema.StringAttribute{
			Description:         "Description is the optional description of the armada set.",
			MarkdownDescription: "Description is the optional description of the armada set.",
			Optional:            true,
		},
		"autoscaling": schema.SingleNestedAttribute{
			Description:         "AutoscalingInterval defines the autoscaling strategy for all armadas.",
			MarkdownDescription: "AutoscalingInterval defines the autoscaling strategy for all armadas.",
			Optional:            true,
			Attributes:          ArmadaAutoscalingAttributes(),
		},
		"regions": schema.ListNestedAttribute{
			Description:         "Regions is a list of regions Armadas will be created in.",
			MarkdownDescription: "Regions is a list of regions Armadas will be created in.",
			Required:            true,
			NestedObject: schema.NestedAttributeObject{
				Attributes: map[string]schema.Attribute{
					"name": schema.StringAttribute{
						Description:         "The name of the region game server are distributed to.",
						MarkdownDescription: "The name of the region game server are distributed to.",
						Required:            true,
					},
					"repicas": schema.ListNestedAttribute{
						Description:         "Replicas specifies the distribution of game servers across the available types of capacity in the selected region.",
						MarkdownDescription: "Replicas specifies the distribution of game servers across the available types of capacity in the selected region.",
						Required:            true,
						NestedObject: schema.NestedAttributeObject{
							Attributes: ArmadaRegionTypeAttributes(),
						},
					},
				},
			},
		},
		"template": schema.SingleNestedAttribute{
			Description:         "Template describes the fleets that are created.",
			MarkdownDescription: "Template describes the fleets that are created.",
			Required:            true,
			Attributes:          FleetTemplateSpecAttributes(),
		},
	}
}
